### ISSUE TITLE
Documentation build

### ISSUE THREAD

**Issue by irushchyshyn** [proycon/pynlpl#23]
Hey Maarten,

I have noticed a couple of issues when building the documentation for the package. I have prepared Pull Requests to fix some of them, and I would appreciate if you could take a look/comment on/merge them.

1) `ImportErrror` traceback:
```
WARNING: [autosummary] failed to import u'pynlpl.formats.folia.AlignmentReference': no module named pynlpl.formats.folia.AlignmentReference
```
This happens because the class is actually named `AlignReference` (https://github.com/proycon/pynlpl/blob/master/formats/folia.py#L4385)
```
/builddir/build/BUILD/pynlpl-1.0.9/docs/lm.rst:8: WARNING: autodoc: failed to import module u'pynlpl.lm.srilm'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 519, in import_object
    __import__(self.modname)
  File "/builddir/build/BUILD/pynlpl/lm/srilm.py", line 21, in <module>
    import srilmcc
ImportError: No module named srilmcc
```
[The SRI Language Modeling Toolkit] (http://www.speech.sri.com/projects/srilm/) is needed to use the `lm.SRILM` model. This is an undocumented dependency which needs to be handled in case it is not configured.
PR: https://github.com/proycon/pynlpl/pull/20

2) `AttributeError` traceback
```
/builddir/build/BUILD/pynlpl-1.0.9/docs/_autosummary/pynlpl.formats.folia.AllowTokenAnnotation.rst:42: WARNING: autodoc: failed to import method u'AllowTokenAnnotation.__iter__' from module u'pynlpl.formats.folia'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 526, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 422, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python2.7/site-packages/sphinx/util/inspect.py", line 125, in safe_getattr
    raise AttributeError(name)
AttributeError: __iter__
/builddir/build/BUILD/pynlpl-1.0.9/docs/_autosummary/pynlpl.formats.folia.AllowTokenAnnotation.rst:43: WARNING: autodoc: failed to import method u'AllowTokenAnnotation.__len__' from module u'pynlpl.formats.folia'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 526, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 422, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python2.7/site-packages/sphinx/util/inspect.py", line 125, in safe_getattr
    raise AttributeError(name)
AttributeError: __len__
```
Happens because `AllowTokenAnnotation` does not have `__len__` and `__iter__`.
PR: https://github.com/proycon/pynlpl/pull/21
3) Warnings
```
docstring of pynlpl.formats.folia.AbstractAnnotationLayer.parsexml:3: WARNING: Inline literal start-string without end-string.
docstring of pynlpl.formats.folia.AbstractElement:13: ERROR: Unexpected indentation.
docstring of pynlpl.formats.folia.AbstractElement:15: WARNING: Block quote ends without a blank line; unexpected unindent.
docstring of pynlpl.formats.folia.AbstractElement.parsexml:3: WARNING: Inline literal start-string without end-string.
docstring of pynlpl.formats.folia.AbstractSpanAnnotation.parsexml:3: WARNING: Inline literal start-string without end-string.
docstring of pynlpl.formats.folia.AbstractStructureElement.parsexml:3: WARNING: Inline literal start-string without end-string.
docstring of pynlpl.formats.folia.AbstractTokenAnnotation.parsexml:3: WARNING: Inline literal start-string without end-string.
docstring of pynlpl.formats.folia.ActorFeature.parsexml:3: WARNING: Inline literal start-string without end-string.
docstring of pynlpl.formats.folia.Alternative.parsexml:3: WARNING: Inline literal start-string without end-string.
docstring of pynlpl.formats.folia.AlternativeLayers.parsexml:3: WARNING: Inline literal start-string without end-string.
docstring of pynlpl.formats.folia.BegindatetimeFeature.parsexml:3: WARNING: Inline literal start-string without end-string.
docstring of pynlpl.formats.folia.Cell.parsexml:3: WARNING: Inline literal start-string without end-string.
docstring of pynlpl.formats.folia.Chunk.parsexml:3: WARNING: Inline literal start-string without end-string.
docstring of pynlpl.formats.folia.ChunkingLayer.parsexml:3: WARNING: Inline literal start-string without end-string.
docstring of pynlpl.formats.folia.CoreferenceChain.parsexml:3: WARNING: Inline literal start-string without end-string.
docstring of pynlpl.formats.folia.CoreferenceLayer.parsexml:3: WARNING: Inline literal start-string without end-string.
docstring of pynlpl.formats.folia.CoreferenceLink.parsexml:3: WARNING: Inline literal start-string without end-string.
....
```
I have fixed some of them in the Pull Request https://github.com/proycon/pynlpl/pull/22

Thank you,
Iryna

**Comment by irushchyshyn** [comment]
Resolving the issue as the PRs were merged. Thanks!
